---
title: "CodeBook"
author: "Xiaonan Xu"
date: "January 16, 2021"
output: html_document
---

# Here are the set of variables in the : 

Mean: Mean value
Standard-deviation: Standard deviation
Median-absolute-deviation: Median absolute deviation 
Largest-value: Largest value in array
Smallest-value: Smallest value in array
Signal-magnitude-area: Signal magnitude area
Energy-measure: Energy measure. Sum of the squares divided by the number of values. 
Interquartile-range: Interquartile range 
Signal-entropy: Signal entropy
Autorregresion-coefficients: Autorregresion coefficients with Burg order equal to 4
Correlation-coefficient: correlation coefficient between two signals
Index-frequency-component: index of the frequency component with largest magnitude
Mean-frequency: Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

